### ISSUE TITLE
森林场景中的参数及效果

### ISSUE THREAD

**Issue by XinZhaoDC** [byangw/PCT_planner#1]
你好，这篇论文是一个很棒的工作。我在论文中看到测试了森林场景以及结果对比，但是在代码中并无该场景的参数与数据，也就没有一个直观的效果展示。我这里也有自己采集的森林场景点云，想测试一下在森林中的效果，请教一下森林场景的参数应该如何设置？另外，对于无人机这种非地面物体，能否做简单调整完成路径规划？谢谢。

**Comment by byangw** [comment]
你好，感谢你的提问。森林场景和其他城市场景的算法原理及参数设置没有很大差别，只需根据不同机器人平台的几何形状设置层析间距及膨胀核尺寸，再根据机器人具体的通行能力设置与travel cost相关的参数即可，相关参数含义在论文中有较详细的解释。我们会考虑近期在仓库中添加一些森林场景的样例。

需要注意，本方法主要关注场景的几何信息进行可通行性评估，关于森林场景的演示旨在说明本文的方法对于不规则几何地形及三维空间依然适用，但尚未考虑真实森林场景复杂的语义及地面物理特性。同时本文的方法需要点云地图有较高的质量，对于真实点云的噪声及空洞较为敏感。（以上详见论文Discussion部分）

本文的场景表达及路径规划方法，从原理上实现更高效率的其中一个前提是，机器人的运动被约束于地面附近。因此，对于无人机而言，如果其运动也被约束于贴近地面飞行，则本方法也可以为其进行路径规划，只需要调整轨迹优化参数来使轨迹满足无人机的动力学约束即可。但鉴于无人机可以穿越高度更狭窄的缝隙，同时其对地面的结构特征并不敏感，因此相比于三维占据体素或SDF，使用多层高程图描述场景可能反而会导致更低的导航效率。

**Comment by XinZhaoDC** [comment]
好的，感谢指导！
